x = float(input("value of x: "))
y = float(input("value of y: "))
ans = 0

ans = x + y
print ("Value of x+y ", ans)

ans = x - y
print ("Value of x-y  ", ans )

ans = x * y
print (" Value of x*y  ", ans )

ans = x / y
print (" Value of x/y  ", ans )

ans = x % y
print ("Value of x % y ",ans)

ans = x**y 
print ("Value of x**y  ", ans)

ans = x//y 
print ("Value of x//y  ", ans)

